version: '3.8'

services:
  translation-provider-api:
    build: .
    container_name: translation-provider-api
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=TranslationProviderDb;User=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=true;
      - ApplicationName=Translation Provider
      - ServiceId=translation-provider
      - ServiceName=Translation Provider Service
      - ServiceVersion=1.0.0
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - translation-provider-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: translation-provider-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P YourStrong@Passw0rd -C -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - translation-provider-network

volumes:
  sqlserver_data:
    driver: local

networks:
  translation-provider-network:
    driver: bridge